name: Update Date File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-file:
    runs-on: self-hosted

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: 日付をファイルに書き込む
        run: echo "$(date '+%Y-%m-%d %H:%M:%S')" > date.txt

      - name: 変更をコミット
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add date.txt
          git commit -m "Update date file"

      - name: 変更をプッシュ
        run: git push
