name: Sample
on:
  - push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Hello world
        run: |
             echo hello, world!
             pwd
             ls -al
